### ISSUE TITLE
Dynamic Code Graph Generator implementation

### ISSUE THREAD

**Issue by iumyx2612** [FSoft-AI4Code/AgileCoder#14]
In your paper, you propose a module called Dynamic Code Graph Generator but I can't seem to find the implementation in this repo. Can you show me?

**Comment by minhngh** [comment]
Hi [iumyx2612](https://github.com/iumyx2612),

Thank you for your concern. The implementation of this module is pretty straightforward because our proposed graph just captures use-define dependency relationships among code files. You can see the code below for graph construction, which will be called whenever the source code is updated
https://github.com/FSoft-AI4Code/AgileCoder/blob/5e55c331fb074b490bd78f51e4d48f76bb78970c/agilecoder/camel/dependency.py#L21

**Comment by iumyx2612** [comment]
Thank you for the fast reply!
